version: '3.8'

services:
  drill:
    build: .
    container_name: drill-unicode-fix
    ports:
      - "37.252.23.30:8047:8047"  # Привязка к внешнему IP
      - "37.252.23.30:31010:31010"
    environment:
      - DRILL_JAVA_OPTS=-Ddrill.exec.options.planner.parser.enable_unicode_literals=false -Dfile.encoding=UTF-8 -Xms128m -Xmx384m
    volumes:
      # Для персистентности логов (опционально)
      - drill_logs:/opt/drill/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8047/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  drill_logs:
