version: '3.8'

services:
  drill:
    image: apache/drill:latest
    container_name: drill-unicode-fix
    ports:
      - "37.252.23.30:8047:8047"   # Web UI
      - "37.252.23.30:31010:31010" # JDBC/ODBC
    environment:
      # Память для маленького сервера (1 GB RAM)
      - DRILL_HEAP=384M
      - DRILL_MAX_DIRECT_MEMORY=256M
      # Убираем старые GC-флаги, ставим современный G1GC + фиксы для Unicode
      - DRILL_JAVA_OPTS=-XX:+UseG1GC -Dfile.encoding=UTF-8 -Ddrill.exec.options.planner.parser.enable_unicode_literals=false
    volumes:
      - drill_logs:/opt/drill/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8047/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  drill_logs:
