version: '3.8'

services:
  drill:
    image: apache/drill:1.22.0
    container_name: drill-service
    command: drillbit.sh run
    ports:
      - "37.252.23.30:8047:8047"
      - "37.252.23.30:31010:31010"
    environment:
      - DRILL_HEAP=256M
      - DRILL_MAX_DIRECT_MEMORY=128M
      - DRILL_JAVA_OPTS=-XX:+UseG1GC -Dfile.encoding=UTF-8 -Ddrill.exec.options.planner.parser.enable_unicode_literals=false
    volumes:
      - drill_logs:/opt/drill/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8047/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  drill_logs:
